#variables
@baseUrl= http://localhost:3333
# @name healthApi
GET {{baseUrl}}/health

###
#Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

### Create Rooms
# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Sala de teste2",
  "description": "Descrição da sala de teste2"
}

###
# @no-log
@roomId = {{getRooms.response.body.$.[0].id}}

###
# @no-log
@createdRoomId = {{createRoom.response.body.$.roomId}}

###
#Get Rooms questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

### Create Questions
# @name createQuestion
# POST {{baseUrl}}/rooms/{{createdRoomId}}/questions
POST {{baseUrl}}/rooms/6b70810c-74ff-4ce9-2665-dbe392f0610b/questions
Accept: application/json
Content-Type: application/json

{
  "question": "O que é react?"
}